# Generated by Django 3.1.6 on 2021-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('requestOne', models.DateField(blank=True, null=True)),
                ('requestTwo', models.DateField(blank=True, null=True)),
                ('requestThree', models.DateField(blank=True, null=True)),
                ('postGradLevel', models.CharField(choices=[('1', 'PGY1'), ('2', 'PGY2'), ('3', 'PGY3'), ('4', 'PGY4'), ('5', 'PGY5')], default=None, max_length=4)),
            ],
        ),
    ]
