# Generated by Django 3.1.6 on 2021-05-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('postGradLevel', models.CharField(choices=[(1, 'PGY1'), (2, 'PGY2'), (3, 'PGY3'), (4, 'PGY4'), (5, 'PGY5')], default=None, max_length=1)),
                ('generatedSchedule', models.JSONField(blank=True, default=dict, null=True)),
                ('blackoutRotations', models.JSONField(blank=True, default=dict, null=True)),
                ('assignedRotations', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
