# Generated by Django 3.1.6 on 2021-05-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='postGradLevel',
            field=models.CharField(choices=[('1', 'PGY1'), ('2', 'PGY2'), ('3', 'PGY3'), ('4', 'PGY4'), ('5', 'PGY5')], default=None, max_length=1),
        ),
    ]
