# Generated by Django 3.1.6 on 2021-05-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210504_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationsByWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotationWeek', models.PositiveIntegerField()),
                ('availableRotations', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
