# Generated by Django 3.1.6 on 2021-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rotationsbyweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationsbyweek',
            name='availableRotations',
            field=models.JSONField(blank=True, default=set, null=True),
        ),
    ]
