# Generated by Django 3.1.6 on 2021-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210505_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationsbyweek',
            name='availableRotations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
