# Generated by Django 3.1.6 on 2021-04-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentRequests',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='useraccess.scheduleruser')),
                ('requestOne', models.DateField(blank=True, null=True)),
                ('requestTwo', models.DateField(blank=True, null=True)),
                ('requestThree', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
