# Generated by Django 3.1.6 on 2021-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentrequests',
            name='ResidentSchedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
