# Generated by Django 3.1.6 on 2021-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleruser',
            name='ResidentSchedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
