# Generated by Django 3.1.6 on 2021-05-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0002_auto_20210502_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleruser',
            name='AccessLevel',
            field=models.CharField(choices=[('NA', 'not applicable'), ('1', 'year 1 resident'), ('2', 'year 2 resident'), ('3', 'year 3 resident'), ('4', 'year 4 resident'), ('5', 'year 5 resident')], max_length=5),
        ),
    ]
