# Generated by Django 3.1.6 on 2021-05-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0003_auto_20210502_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleruser',
            name='AccessLevel',
            field=models.CharField(choices=[('NA', 'not applicable'), ('1', 'PGY1'), ('2', 'PGY2'), ('3', 'PGY3'), ('4', 'PGY4'), ('5', 'PGY5')], max_length=2),
        ),
    ]
