# Generated by Django 3.1.6 on 2021-05-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0004_auto_20210502_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleruser',
            name='ResidentSchedule',
        ),
    ]
