# Generated by Django 3.1.6 on 2021-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='EndRotation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteria',
            name='Essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criteria',
            name='Overnight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criteria',
            name='ResidentYear',
            field=models.CharField(choices=[('NA', 'not applicable'), ('PGY1', 'year 1 resident'), ('PGY2', 'year 2 resident'), ('PGY3', 'year 3 resident'), ('PGY4', 'year 4 resident'), ('PGY5', 'year 5 resident')], default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='criteria',
            name='StartRotation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
