# Generated by Django 3.1.6 on 2021-05-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_auto_20210326_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='ResidentYear',
            field=models.CharField(choices=[('NA', 'not applicable'), ('1', 'PGY1'), ('2', 'PGY2'), ('3', 'PGY3'), ('4', 'PGY4'), ('5', 'PGY5')], default=None, max_length=20),
        ),
    ]
