# Generated by Django 3.1.6 on 2021-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_auto_20210503_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='MaxContinuedWeeks',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteria',
            name='MinContinuedWeeks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
